// Mocks generated by Mockito 5.4.0 from annotations
// in app/test/Routing/RouteCreators/advanced_route_creator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/MapData/Loaders/bus_route_geojson_loader.dart' as _i5;
import 'package:app/Routing/location.dart' as _i4;
import 'package:app/Routing/Servers/routing_server.dart' as _i2;
import 'package:app/Wrapper/date_time_wrapper.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RoutingServer].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutingServer extends _i1.Mock implements _i2.RoutingServer {
  MockRoutingServer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getResponseBody(
    _i4.Location? startLocation,
    _i4.Location? endLocation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResponseBody,
          [
            startLocation,
            endLocation,
          ],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
  @override
  String getUriDomains() => (super.noSuchMethod(
        Invocation.method(
          #getUriDomains,
          [],
        ),
        returnValue: '',
      ) as String);
}

/// A class which mocks [BusRouteGeoJsonLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusRouteGeoJsonLoader extends _i1.Mock
    implements _i5.BusRouteGeoJsonLoader {
  MockBusRouteGeoJsonLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getBusRouteGeoJson() => (super.noSuchMethod(
        Invocation.method(
          #getBusRouteGeoJson,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<String> getBusRouteGeoJsonAsString() => (super.noSuchMethod(
        Invocation.method(
          #getBusRouteGeoJsonAsString,
          [],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}

/// A class which mocks [DateTimeWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeWrapper extends _i1.Mock implements _i6.DateTimeWrapper {
  MockDateTimeWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
      ) as DateTime);
}
